name: mindweave
description: "MindWeave - Your elegant solution for capturing thoughts, organizing ideas, and effortlessly sharing information, featuring intuitive copy blocks for one-tap text extraction."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Styling
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  
  # State & Storage
  shared_preferences: ^2.3.3
  
  # Utilities
  url_launcher: ^6.3.1
  intl: ^0.19.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
